name: "github actions build and deploy gh-pages"
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: install and build
        run: |
          npm install
          npm run build

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDENcDRZAPHZ6BNJTmsvJuS41+XgAs5dUm3RxJ/4Z6nAk/atismBG6H9fhzkVf9tqNLa/EutWr8zKFe+e5IeE1mI4Hmp6t1celnu9TdFD4SkoOPAMN15LotrS9ZhTRI+kwklnnEip6wWC0nJoEXxXyaZH2UuNnSCL4SmU4AqBg9PbsRt1JlhoyjZ1nA5g84jKmOq9+Azdj+z8daXHFIhnQ4d/XYEGArfLPZEr5UGBSlHMW4gbqWf5rt4ULRyRtXZaO/3ZcI2zuSdaHcs9XDRIdztAncmjc3rgA8hvRb786uLoGaHZ45XvhyxqQysYWx+KpwhcjhYho9hHcOOFwjjlcJ chaoquny@cn.ibm.com

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: dist
